name: FanZone Frontend CI

on:
push:
branches: [ "main" ]

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  # -------------------
  # ğŸ“¥ Checkout code
  # -------------------
  - name: Checkout repository
    uses: actions/checkout@v3

  # -------------------
  # ğŸŸ§ Setup Node.js
  # -------------------
  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '20'

  # -------------------
  # ğŸ“¦ Install dependencies
  # -------------------
  - name: Install React dependencies
    run: |
      cd front_end
      npm install

  # -------------------
  # ğŸ› ï¸ Build React/Vite
  # -------------------
  - name: Build React
    run: |
      cd front_end
      npm run build


```
